<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="8" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="25023" started-at="2019-01-02T06:56:23Z" finished-at="2019-01-02T06:56:48Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="25023" started-at="2019-01-02T06:56:23Z" finished-at="2019-01-02T06:56:48Z">
      <class name="testcases.ExcuteTest">
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:testcases.ExcuteTest@4cdbe50f]" name="setUp" is-config="true" duration-ms="3427" started-at="2019-01-02T06:56:23Z" finished-at="2019-01-02T06:56:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="launchFlightReservationApplication()[pri:0, instance:testcases.ExcuteTest@4cdbe50f]" name="launchFlightReservationApplication" duration-ms="4159" started-at="2019-01-02T06:56:26Z" finished-at="2019-01-02T06:56:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchFlightReservationApplication -->
        <test-method status="PASS" signature="verifyLinks()[pri:0, instance:testcases.ExcuteTest@4cdbe50f]" name="verifyLinks" duration-ms="1521" started-at="2019-01-02T06:56:30Z" depends-on-methods="testcases.ExcuteTest.launchFlightReservationApplication" finished-at="2019-01-02T06:56:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLinks -->
        <test-method status="SKIP" signature="testSkip()[pri:0, instance:testcases.ExcuteTest@4cdbe50f]" name="testSkip" duration-ms="0" started-at="2019-01-02T06:56:30Z" finished-at="2019-01-02T06:56:30Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[This test got skipped as it was not ready to be executed.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: This test got skipped as it was not ready to be executed.
at testcases.ExcuteTest.testSkip(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.TestNG.privateMain(TestNG.java:1354)
at org.testng.TestNG.main(TestNG.java:1323)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSkip -->
        <test-method status="FAIL" signature="testFail()[pri:0, instance:testcases.ExcuteTest@4cdbe50f]" name="testFail" duration-ms="0" started-at="2019-01-02T06:56:30Z" finished-at="2019-01-02T06:56:30Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at testcases.ExcuteTest.testFail(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.TestNG.privateMain(TestNG.java:1354)
at org.testng.TestNG.main(TestNG.java:1323)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFail -->
        <test-method status="PASS" signature="verifyWebTable()[pri:0, instance:testcases.ExcuteTest@4cdbe50f]" name="verifyWebTable" duration-ms="2044" started-at="2019-01-02T06:56:32Z" depends-on-methods="testcases.ExcuteTest.verifyLinks" finished-at="2019-01-02T06:56:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyWebTable -->
        <test-method status="PASS" signature="login()[pri:0, instance:testcases.ExcuteTest@4cdbe50f]" name="login" duration-ms="7435" started-at="2019-01-02T06:56:34Z" depends-on-methods="testcases.ExcuteTest.verifyWebTable" finished-at="2019-01-02T06:56:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="reserveAFlight()[pri:0, instance:testcases.ExcuteTest@4cdbe50f]" name="reserveAFlight" duration-ms="3657" started-at="2019-01-02T06:56:41Z" depends-on-methods="testcases.ExcuteTest.login" finished-at="2019-01-02T06:56:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reserveAFlight -->
        <test-method status="PASS" signature="bookATicket()[pri:0, instance:testcases.ExcuteTest@4cdbe50f]" name="bookATicket" duration-ms="2045" started-at="2019-01-02T06:56:45Z" depends-on-methods="testcases.ExcuteTest.reserveAFlight" finished-at="2019-01-02T06:56:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bookATicket -->
        <test-method status="PASS" signature="closeDriver()[pri:0, instance:testcases.ExcuteTest@4cdbe50f]" name="closeDriver" is-config="true" duration-ms="711" started-at="2019-01-02T06:56:47Z" finished-at="2019-01-02T06:56:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- testcases.ExcuteTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
